# Generated by Django 4.0.10 on 2023-10-14 01:42

import comics.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('cover', models.ImageField(blank=True, upload_to=comics.models.generate_comic_path)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('special_status', 'Can read all comics')],
            },
        ),
        migrations.CreateModel(
            name='ComicChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='comics.comic')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='comics.comic')),
            ],
        ),
        migrations.CreateModel(
            name='ComicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('img', models.ImageField(blank=True, upload_to=comics.models.generate_comic_path)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='comics.comicchapter')),
            ],
        ),
        migrations.AddConstraint(
            model_name='comicpage',
            constraint=models.UniqueConstraint(fields=('chapter', 'page'), name='unique_chapter_page'),
        ),
        migrations.AddConstraint(
            model_name='comicchapter',
            constraint=models.UniqueConstraint(fields=('comic', 'chapter'), name='unique_comic_chapter'),
        ),
    ]
