# Generated by Django 4.0.10 on 2024-11-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_alter_comicchapter_options_comic_id_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comicchapter',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comicpage',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
